### ISSUE TITLE
multiple threads are not in use

### ISSUE THREAD

**Issue by tinyfallen** [JLSteenwyk/orthohmm#13]
Hi dear developers,

Thanks for your scripts! I run the command with 70 threads (-c 70) and found phmmer can not make use of multiple threads, so it is too slow. Maybe you could make a parallel pipeline for the phmmer step.

Best regards.

**Comment by JLSteenwyk** [comment]
Hi @tinyfallen,

Thanks for writing and your inquiry!

OrthoHMM version 0.1.0 now handles the phmmer subprocesses differently. Specifically, the subprocesses are spread across multiple threads so that multiple phmmer commands can run simultaneously.

Version 0.1.0 is available on PyPi [https://pypi.org/project/orthohmm/](https://pypi.org/project/orthohmm/).

Happy holidays and happy coding!

Regards,

Jacob

**Comment by tinyfallen** [comment]
Thank you Jacob, merry Christmas ~

**Comment by JLSteenwyk** [comment]
Merry Christmas, @tinyfallen!!

Wishing you all the best in 2025 and beyond!
